### ISSUE TITLE
Does not work on PHP 7.3

### ISSUE THREAD

**Issue by irkallacz** [caxy/php-htmldiff#79]
I try to use it on PHP 7.3. and I got `Warning: preg_match(): Compilation failed: invalid range in character class at offset 4`

What I found that PHP 7.3. use PCRE2: http://php.net/manual/en/migration73.other-changes.php#migration73.other-changes.pcre witch cause problem in php simple html dom parser https://github.com/sunra/php-simple-html-dom-parser/issues/64

First option is use different library like https://github.com/Kub-AT/php-simple-html-dom-parser

Second options is wait until sunra/php-simple-html-dom-parser have new version.

**Comment by jschroed91** [comment]
I'd like to move away from the dependency at some point altogether - but switching to the other repository which has the latest updates of the original package seems like an OK solution for 7.3 support.

I'm not able to test switching the lib today, but will do that early this week - if someone opens a PR w/ the changes I'd take that as well :)

**Comment by matthewgoslett** [comment]
This is still a problem for me on latest version 0.1.9.

<img width="845" alt="screenshot_1344" src="https://user-images.githubusercontent.com/1571743/60652957-6244fb80-9e49-11e9-9410-695049087ad2.png">

**Comment by SavageTiger** [comment]
@matthewgoslett @irkallacz Do you have the same when you run functional tests on 7.3?
